setGeneric("setLoc<-",function(model,value){standardGeneric("setLoc<-")}) 
setGeneric("setGeneName<-",function(model,value){standardGeneric("setGeneName<-")}) 
setGeneric("setChromosome<-",function(model, value){standardGeneric ("setChromosome<-")})
setGeneric("setArm<-",function(model, value){standardGeneric ("setArm<-")})
setGeneric("getLoc",function(model){standardGeneric ("getLoc")}) 
setGeneric("getGeneName",function(model){standardGeneric ("getGeneName")}) 
setGeneric("getGeneNames",function(model){standardGeneric ("getGeneNames")}) 
setGeneric("getChromosome",function(model){standardGeneric ("getChromosome")}) 
setGeneric("getArm",function(model){standardGeneric ("getArm")}) 
setGeneric("getPArm",function(model){standardGeneric ("getPArm")}) 
setGeneric("getQArm",function(model){standardGeneric ("getQArm")}) 
setGeneric("topGenes",function(model,num = NA){standardGeneric ("topGenes")}) 
setGeneric("topModels",function(model,num = 1){standardGeneric ("topModels")}) 
setGeneric("getModelNumbers",function(model){standardGeneric ("getModelNumbers")})
setGeneric("isEmpty",function(model){standardGeneric ("isEmpty")})
setGeneric("orderGenes",function(model){standardGeneric ("orderGenes")})
setGeneric("findModel",function(model, name){standardGeneric ("findModel")})
